a = int(15)
b = int(a/2)
c = float(15.456)
d = float(c/7)

print("Valores de b:")
print("-------------")
print("1) b = %d" %b)
print("2) b = %20d" %b)
print("3) b = %020d" %b)
print("4) b = %-20d" %b)
print("5) b = %d%%" %b)
print()
print("Valores de d:")
print("-------------")
print("1) d = %f" %d)
print("2) d = %d" %d)
print("3) d = %0.1f" %d)
print("4) d = %0.2f" %d)
print("5) d = %0.3f" %d)
print("6) d = %20.3f" %d)
print("7) d = %020.3f" %d)
print("8) d = %-20.3f" %d)
print("9) d = %0.2f%%" %d)