primeiro = input()
segundo = input()
terceiro = input()
quarto = input()
quinto = input()
sexto = input()
setimo = input()
oitavo = input()
nono = input()
dez = input()

print(terceiro)
print(setimo)
print(nono)